version: '3.9'

services:
  db:
    container_name: godb
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
    - "1337:5432"
    volumes:
      - pgdata:/var/lib/postgresql12/data
volumes:
  pgdata: {}